analyzer:
  exclude:
    - "**/*repo.g.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"

include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
