name: little_flutter_assessment
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.2.0
  core_repository:
    path: packages/core_repository
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.18.0
  pokemon_repository:
    path: packages/pokemon_repository
  riverpod_annotation: ^2.1.1

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
