name: little_flutter_assessment
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  intl: ^0.18.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
