name: core_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  riverpod_repo: ^1.0.11

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.3
  riverpod_test: ^0.1.3
  very_good_analysis: ^5.0.0
